import { CourseCard, type CourseCardProps } from "@/components/reusable/course-card";
import { cn } from "@/lib/utils";

export interface CourseItem extends CourseCardProps {
  id?: string;
  numericPrice?: number;
  level?: "Beginner" | "Intermediate" | "Advanced" | "All Levels";
  featured?: boolean;
}

export const ALL_COURSES: CourseItem[] = [
  {
    id: "1",
    title: "Learn Figma from Basic",
    creator: "PurePearl Studio",
    category: "UI/UX Design",
    level: "Beginner",
    price: "$25",
    numericPrice: 25,
    tone: "mint",
    rating: "4.8",
    featured: true,
    badges: ["17 Lessons", "2 hours 16 mins", "59 Comments"],
    image: "https://images.unsplash.com/photo-1586717791821-3f44a563fa4c?auto=format&fit=crop&w=900&q=85",
  },
  {
    id: "2",
    title: "Build Digital Asset",
    creator: "PurePearl Studio",
    category: "UI/UX Design",
    level: "Intermediate",
    price: "$25",
    numericPrice: 25,
    tone: "coral",
    rating: "4.7",
    featured: true,
    badges: ["14 Lessons", "3 hours 10 mins", "42 Comments"],
    image: "https://images.unsplash.com/photo-1558655146-d09347e92766?auto=format&fit=crop&w=900&q=85",
  },
  {
    id: "3",
    title: "Music Production & Sound Design",
    creator: "SoundWave Academy",
    category: "Music",
    level: "All Levels",
    price: "$35",
    numericPrice: 35,
    tone: "violet",
    rating: "4.9",
    featured: true,
    badges: ["22 Lessons", "4 hours 45 mins", "88 Comments"],
    image: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=900&q=85",
  },
  {
    id: "4",
    title: "Watercolor & Acrylic Expressive Painting",
    creator: "Elena Vance",
    category: "Drawing & Painting",
    level: "Beginner",
    price: "$22",
    numericPrice: 22,
    tone: "mint",
    rating: "4.6",
    featured: true,
    badges: ["18 Lessons", "3 hours 20 mins", "64 Comments"],
    image: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=900&q=85",
  },
  {
    id: "5",
    title: "Performance & Growth Marketing 2026",
    creator: "Nexus Strategy",
    category: "Marketing",
    level: "Intermediate",
    price: "$28",
    numericPrice: 28,
    tone: "coral",
    rating: "4.8",
    featured: true,
    badges: ["25 Lessons", "5 hours 12 mins", "102 Comments"],
    image: "https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&w=900&q=85",
  },
  {
    id: "6",
    title: "3D Character Animation in Blender",
    creator: "PixelCraft Motion",
    category: "Animation",
    level: "Advanced",
    price: "$40",
    numericPrice: 40,
    tone: "violet",
    rating: "4.9",
    featured: true,
    badges: ["32 Lessons", "6 hours 40 mins", "145 Comments"],
    image: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=900&q=85",
  },
  {
    id: "7",
    title: "Viral Short-Form Content Blueprint",
    creator: "Aria Moore",
    category: "Social Media",
    level: "Beginner",
    price: "$20",
    numericPrice: 20,
    tone: "mint",
    rating: "4.7",
    featured: true,
    badges: ["12 Lessons", "2 hours 05 mins", "73 Comments"],
    image: "https://images.unsplash.com/photo-1611162617474-5b21e879e113?auto=format&fit=crop&w=900&q=85",
  },
  {
    id: "8",
    title: "Brand Storytelling & Creative Copy",
    creator: "PurePearl Studio",
    category: "Creative Marketing",
    level: "Intermediate",
    price: "$25",
    numericPrice: 25,
    tone: "coral",
    rating: "4.5",
    featured: true,
    badges: ["15 Lessons", "2 hours 45 mins", "38 Comments"],
    image: "https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=900&q=85",
  },
  {
    id: "9",
    title: "Artisanal Bread & Sourdough Secrets",
    creator: "Chef Antoine",
    category: "Cooking",
    level: "All Levels",
    price: "$26",
    numericPrice: 26,
    tone: "violet",
    rating: "4.9",
    featured: true,
    badges: ["16 Lessons", "3 hours 15 mins", "91 Comments"],
    image: "https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&w=900&q=85",
  },
  {
    id: "10",
    title: "Acoustic Guitar Mastery for Beginners",
    creator: "Leo Strings",
    category: "Music",
    level: "Beginner",
    price: "$19",
    numericPrice: 19,
    tone: "mint",
    rating: "4.6",
    featured: false,
    badges: ["20 Lessons", "3 hours 50 mins", "54 Comments"],
    image: "https://images.unsplash.com/photo-1510915361894-db8b60106cb1?auto=format&fit=crop&w=900&q=85",
  },
  {
    id: "11",
    title: "Oil Painting Techniques & Light Theory",
    creator: "Elena Vance",
    category: "Drawing & Painting",
    level: "Advanced",
    price: "$34",
    numericPrice: 34,
    tone: "violet",
    rating: "4.8",
    featured: false,
    badges: ["24 Lessons", "4 hours 30 mins", "82 Comments"],
    image: "https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=900&q=85",
  },
  {
    id: "12",
    title: "Master French Sauces & Culinary Skills",
    creator: "Chef Marcus",
    category: "Cooking",
    level: "Intermediate",
    price: "$24",
    numericPrice: 24,
    tone: "coral",
    rating: "4.7",
    featured: false,
    badges: ["14 Lessons", "2 hours 30 mins", "40 Comments"],
    image: "https://images.unsplash.com/photo-1507048331197-7d4ac70811cf?auto=format&fit=crop&w=900&q=85",
  },
  {
    id: "13",
    title: "Advanced Design Systems & Tokens",
    creator: "PurePearl Studio",
    category: "UI/UX Design",
    level: "Advanced",
    price: "$35",
    numericPrice: 35,
    tone: "mint",
    rating: "4.9",
    featured: false,
    badges: ["20 Lessons", "4 hours 10 mins", "67 Comments"],
    image: "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=900&q=85",
  },
  {
    id: "14",
    title: "Modern Electronic Music & Synthesizers",
    creator: "SoundWave Academy",
    category: "Music",
    level: "Intermediate",
    price: "$30",
    numericPrice: 30,
    tone: "violet",
    rating: "4.8",
    featured: false,
    badges: ["18 Lessons", "3 hours 40 mins", "49 Comments"],
    image: "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&w=900&q=85",
  },
  {
    id: "15",
    title: "Botanical Illustration in Gouache",
    creator: "Elena Vance",
    category: "Drawing & Painting",
    level: "Beginner",
    price: "$22",
    numericPrice: 22,
    tone: "coral",
    rating: "4.7",
    featured: false,
    badges: ["15 Lessons", "2 hours 50 mins", "31 Comments"],
    image: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=900&q=85",
  },
  {
    id: "16",
    title: "SEO Mastery & Technical Optimization",
    creator: "Nexus Strategy",
    category: "Marketing",
    level: "Intermediate",
    price: "$29",
    numericPrice: 29,
    tone: "mint",
    rating: "4.6",
    featured: false,
    badges: ["21 Lessons", "4 hours 15 mins", "83 Comments"],
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=900&q=85",
  },
  {
    id: "17",
    title: "Motion Graphics in After Effects",
    creator: "PixelCraft Motion",
    category: "Animation",
    level: "Intermediate",
    price: "$32",
    numericPrice: 32,
    tone: "violet",
    rating: "4.9",
    featured: false,
    badges: ["26 Lessons", "5 hours 00 mins", "95 Comments"],
    image: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=900&q=85",
  },
  {
    id: "18",
    title: "Instagram Reel Growth & Short Video",
    creator: "Aria Moore",
    category: "Social Media",
    level: "All Levels",
    price: "$21",
    numericPrice: 21,
    tone: "coral",
    rating: "4.7",
    featured: false,
    badges: ["14 Lessons", "2 hours 20 mins", "62 Comments"],
    image: "https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?auto=format&fit=crop&w=900&q=85",
  },
  {
    id: "19",
    title: "Visual Brand Identity & Typography",
    creator: "PurePearl Studio",
    category: "Creative Marketing",
    level: "Beginner",
    price: "$24",
    numericPrice: 24,
    tone: "mint",
    rating: "4.8",
    featured: false,
    badges: ["16 Lessons", "3 hours 00 mins", "44 Comments"],
    image: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=900&q=85",
  },
  {
    id: "20",
    title: "Authentic Italian Pasta from Scratch",
    creator: "Chef Antoine",
    category: "Cooking",
    level: "Beginner",
    price: "$25",
    numericPrice: 25,
    tone: "violet",
    rating: "4.9",
    featured: false,
    badges: ["12 Lessons", "2 hours 15 mins", "78 Comments"],
    image: "https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=900&q=85",
  },
  {
    id: "21",
    title: "Micro-interactions & UX Prototyping",
    creator: "PurePearl Studio",
    category: "UI/UX Design",
    level: "Intermediate",
    price: "$28",
    numericPrice: 28,
    tone: "coral",
    rating: "4.8",
    featured: false,
    badges: ["17 Lessons", "3 hours 30 mins", "51 Comments"],
    image: "https://images.unsplash.com/photo-1581291518655-9523c932deda?auto=format&fit=crop&w=900&q=85",
  },
  {
    id: "22",
    title: "Piano & Keyboard Chords for Songwriting",
    creator: "Leo Strings",
    category: "Music",
    level: "All Levels",
    price: "$27",
    numericPrice: 27,
    tone: "mint",
    rating: "4.7",
    featured: false,
    badges: ["19 Lessons", "3 hours 45 mins", "60 Comments"],
    image: "https://images.unsplash.com/photo-1520523839898-507127053e14?auto=format&fit=crop&w=900&q=85",
  },
  {
    id: "23",
    title: "Digital Concept Art & Environment Design",
    creator: "Elena Vance",
    category: "Drawing & Painting",
    level: "Advanced",
    price: "$38",
    numericPrice: 38,
    tone: "violet",
    rating: "4.9",
    featured: false,
    badges: ["28 Lessons", "5 hours 30 mins", "112 Comments"],
    image: "https://images.unsplash.com/photo-1547891654-e66ed7ebb968?auto=format&fit=crop&w=900&q=85",
  },
  {
    id: "24",
    title: "Email Marketing Automation Strategies",
    creator: "Nexus Strategy",
    category: "Marketing",
    level: "Beginner",
    price: "$23",
    numericPrice: 23,
    tone: "coral",
    rating: "4.6",
    featured: false,
    badges: ["15 Lessons", "2 hours 40 mins", "39 Comments"],
    image: "https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=900&q=85",
  },
  {
    id: "25",
    title: "Stop Motion & Claymation Fundamentals",
    creator: "PixelCraft Motion",
    category: "Animation",
    level: "Beginner",
    price: "$26",
    numericPrice: 26,
    tone: "mint",
    rating: "4.8",
    featured: false,
    badges: ["18 Lessons", "3 hours 10 mins", "47 Comments"],
    image: "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=900&q=85",
  },
  {
    id: "26",
    title: "TikTok Algorithm Mastery & Viral Formats",
    creator: "Aria Moore",
    category: "Social Media",
    level: "Intermediate",
    price: "$22",
    numericPrice: 22,
    tone: "violet",
    rating: "4.7",
    featured: false,
    badges: ["16 Lessons", "2 hours 50 mins", "85 Comments"],
    image: "https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?auto=format&fit=crop&w=900&q=85",
  },
  {
    id: "27",
    title: "Creative Ad Campaigns & Copywriting",
    creator: "PurePearl Studio",
    category: "Creative Marketing",
    level: "Advanced",
    price: "$33",
    numericPrice: 33,
    tone: "coral",
    rating: "4.9",
    featured: false,
    badges: ["22 Lessons", "4 hours 15 mins", "93 Comments"],
    image: "https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?auto=format&fit=crop&w=900&q=85",
  },
  {
    id: "28",
    title: "Asian Street Food & Wok Techniques",
    creator: "Chef Marcus",
    category: "Cooking",
    level: "Intermediate",
    price: "$27",
    numericPrice: 27,
    tone: "mint",
    rating: "4.8",
    featured: false,
    badges: ["17 Lessons", "3 hours 00 mins", "56 Comments"],
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=900&q=85",
  },
  {
    id: "29",
    title: "Mobile App UI Design in Figma",
    creator: "PurePearl Studio",
    category: "UI/UX Design",
    level: "Beginner",
    price: "$25",
    numericPrice: 25,
    tone: "violet",
    rating: "4.7",
    featured: false,
    badges: ["15 Lessons", "2 hours 45 mins", "41 Comments"],
    image: "https://images.unsplash.com/photo-1551650975-87deedd944c3?auto=format&fit=crop&w=900&q=85",
  },
  {
    id: "30",
    title: "Vocal Recording & Mixing in Logic Pro",
    creator: "SoundWave Academy",
    category: "Music",
    level: "Advanced",
    price: "$36",
    numericPrice: 36,
    tone: "coral",
    rating: "4.9",
    featured: false,
    badges: ["24 Lessons", "4 hours 50 mins", "104 Comments"],
    image: "https://images.unsplash.com/photo-1598653222000-6b7b7a552625?auto=format&fit=crop&w=900&q=85",
  },
];

export interface CourseGridProps {
  courses?: CourseItem[];
  className?: string;
  emptyMessage?: string;
}

export function CourseGrid({
  courses = ALL_COURSES.slice(0, 6),
  className,
  emptyMessage = "No courses found matching your criteria.",
}: CourseGridProps) {
  if (courses.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center rounded-2xl border border-dashed border-neutral-200 py-16 text-center">
        <p className="text-base font-semibold text-neutral-800">{emptyMessage}</p>
        <p className="mt-1 text-sm text-neutral-500">
          Try choosing another category or clearing your filters.
        </p>
      </div>
    );
  }

  return (
    <div
      className={cn(
        "grid grid-cols-1 gap-5.5 sm:grid-cols-2 lg:grid-cols-3 max-md:gap-3",
        className
      )}
    >
      {courses.map((course) => (
        <CourseCard key={course.title} {...course} />
      ))}
    </div>
  );
}
